### ISSUE TITLE
Beta release checklist

### ISSUE THREAD

**Issue by RoelN** [Wakamai-Fondue/wakamai-fondue-site#70]
# Site

- [x] Update Font.js. See [engine](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/25) and [Font.js](https://github.com/Wakamai-Fondue/Font.js/pull/2) PRs (which currently use a slightly outdated Font.js) (@pascalw)
- [x] Merge "Show categorised chars" https://github.com/Wakamai-Fondue/wakamai-fondue-site/pull/69 + https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/24 which is finished but needs review (@pascalw)
- [x] Show characters belonging to a GSUB/GPOS layout feature. ~Depends on [Font.js](https://github.com/Pomax/Font.js/pull/89)~ **IN PROGRESS:** https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/32
- [x] Pick example font to open beta with (currently Bungee). Should be variable + have some (interesting) layout features. → Will be DJR's Gimlet 💖 Permission given, now just need to add it.
- [x] Add old language support check
- [x] Improve tester layout and colors
- [x] Offer a way to disable axes (specifically `opsz`). Relevant [issue](https://github.com/Wakamai-Fondue/wakamai-fondue-site/issues/12).
- [ ] Be smart about loading assets in WF and WF engine. Relevant [issue](https://github.com/Wakamai-Fondue/wakamai-fondue-site/issues/26). (@pascalw)

Lower prio:

- [x] Add sticky menu (global) and submenu (variable options w/ grid)
- [ ] Add layout variants to grid
- [x] Add info modal

# NPM

- [ ] Update to latest (Font.js) engine
- [ ] Add documentation/blog post?

**Comment by RoelN** [comment]
Closing this now the beta is live :-)
